<?php
if ($setpg == "pages" AND (($edit == "yes" AND $pgid) OR $add == "yes")) $submode = "update";
else if ($setpg == "pages" AND ($del == "check" AND $pgid)) $submode = "delete";
else if ($setpg == "images" AND $imagedir) $submode = "general";
else if ($setpg == "images" AND $fcn == "update") $submode = "catalog";
else if ($setpg == "categories" AND (($catid AND $Submit == "Edit") OR $Submit == "Add")) $submode = "update";
else if ($setpg == "categories" AND $catid AND $Submit == "Delete") $submode = "delete";
else if ($setpg == "items" AND (($itemid AND $Submit == "Edit") OR $Submit == "Add")) $submode = "update";
else if ($setpg == "items" AND $Submit == "Delete") $submode = "delete";
else if ($setpg == "itemlist" AND $adminsrc == "multi") $submode = "multiple";
else if ($setpg == "itemlist" AND $adminsrc == "standard") $submode = "list";
else if ($setpg == "orders" AND $smo AND $syr AND $emo AND $eyr) $submode = "list";
else if ($setpg == "orders" AND $mode == "Update Details") $submode = "details";
else if ($setpg == "orders" AND $mode == "Update Details") $submode = "update";
else if ($setpg == "orders" AND $mode == "delord") $submode = "delete";
else if ($setpg == "sales" AND $startmonth AND $startyear AND $endmonth AND $endyear) $submode = "list";
else if ($setpg == "sales" AND (($mode == "updsales" AND $saleid) OR $mode == "Add New Sale")) $submode = "update";
else if ($setpg == "sales" AND $mode == "delsales" AND $saleid) $submode = "delete";
else if ($setpg == "sales" AND $mode == "bestsellers") $submode = "bestsellers";
else if ($setpg == "popup" AND (($popup == "Edit" AND $popupid) OR $popup == "Add")) $submode = "update";
else if ($setpg == "popup" AND $popup == "Delete" AND $popupid) $submode = "delete";
else if ($setpg == "coupons" AND (($mode == "Edit" AND $mid) OR $mode == "Add")) $submode = "update";
else if ($setpg == "coupons" AND $mode == "Delete" AND $mid) $submode = "delete";
else if ($setpg == "coupons" AND $mode == "Get Code" AND $mid) $submode = "code";
else if ($setpg == "global" AND $mode == "saleprice") $submode = "sales";
else if ($setpg == "global" AND $mode == "delete") $submode = "delete";
else if ($setpg == "global" AND $mode == "upload") $submode = "upload";
else if ($setpg == "registry" AND $md == "find") $submode = "list";
else if ($setpg == "registry" AND $md == "dp") $submode = "update";
else if ($setpg == "registry" AND $md == "del") $submode = "delete";
else if ($setpg == "wholesale" AND $Submit == "List") $submode = "list";
else if ($setpg == "wholesale" AND (($Submit == "Edit" AND $wsid) OR $Submit == "Add")) $submode = "update";
else if ($setpg == "wholesale" AND $Submit == "Delete") $submode = "delete";
else if ($setpg == "certificates" AND $mode == "Search") $submode = "list";
else if ($setpg == "certificates" AND (($mode == "edit" AND $gcid) OR $mode == "add")) $submode = "update";
else if ($setpg == "certificates" AND $mode == "delete" AND $gcid) $submode = "delete";
else if ($setpg == "events" AND (($mode == "edit" AND $eventid) OR $mode == "add")) $submode = "update";
else if ($setpg == "events" AND $mode == "delete" AND $eventid) $submode = "delete";
else if ($setpg == "weblinks" AND (($mode == "edit" AND $linkid) OR $mode == "add")) $submode = "update";
else if ($setpg == "weblinks" AND $mode == "delete" AND $linkid) $submode = "delete";
else if ($setpg == "guestbook" AND (($mode == "edit" AND $gbid) OR $mode == "add")) $submode = "update";
else if ($setpg == "guestbook" AND $mode == "delete" AND $gbid) $submode = "delete";
else if ($setpg == "articles" AND (($mode == "Edit" AND $artid) OR $mode == "Add")) $submode = "update";
else if ($setpg == "articles" AND $mode == "Delete" AND $artid) $submode = "delete";
else if ($setpg == "faqs" AND (($mode == "Edit" AND $faqid) OR $mode == "Add")) $submode = "update";
else if ($setpg == "faqs" AND $mode == "Delete" AND $faqid) $submode = "delete";
else $submode = "";
?>
